title: Автопарк
author: Ладик Алина, Сергиенко Лев, Шейнин Василий, Башев Ян
description: > # this means to ignore newlines until "baseurl:"
  Проект "Foodie"

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-cayman
